language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - liblapack-dev
            - libblas-dev
            - libmetis-dev
            - gfortran
    - os: osx
      addons:
        homebrew:
          packages:
            - metis
    - os: windows

before_script:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./buildf2c_osx.sh; fi

script:
  - ./build.sh
