image:
  - Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64

install:
  - sh download.sh

build_script:
  - rmdir /s /Q C:\OpenSSL-Win32 C:\OpenSSL-Win64 
  - SET TAUCS_BUILD_DIR=%cd%
  - build_win.bat

